services:
  - type: web
    name: chatbot-backend
    env: node
    buildCommand: cd chatbot-backend && npm install
    startCommand: cd chatbot-backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
  - type: web
    name: chatbot-frontend
    env: static
    rootDir: chatbot-frontend
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_ENV
        value: production 