services:
  - type: web
    name: chatbot-frontend
    env: static
    rootDir: .
    buildCommand: cd chatbot-frontend && npm install && npm run build
    staticPublishPath: chatbot-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_ENV
        value: production 