services:
  - type: web
    name: chatbot-frontend
    env: static
    rootDir: chatbot-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_ENV
        value: production 